component: website
name: website-G2P7It0rKx
org: '1255865753'
app: archos
stage: prod
inputs:
  region: ap-beijing
  src:
    error: index.html
    exclude:
      - .env
    index: index.html
    src: ./
  bucketName: sls-website-ap-beijing-6w53xck