component: website
name: expoundLandingPage
app: expound-landing-page-2e153bd0

inputs:
  src:
    src: ./static
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: expound-landing-page
  protocol: https
